// Generated by CoffeeScript 1.4.0
(function() {

  define(['jquery', 'controller/loading', 'controller/screen1', 'view/loading', 'view/screen1'], function($, LoadingController, Screen1Controller, LoadingView, Screen1View) {
    var Core;
    return Core = (function() {

      function Core() {}

      Core.prototype.init = function() {
        var _this = this;
        console.log('Init Core');
        this.loadingView = new LoadingView('#loading');
        this.loadingController = new LoadingController(this.loadingView);
        this.screen1View = new Screen1View('#screen1');
        this.screen1Controller = new Screen1Controller(this.screen1View);
        this.loadingController.load();
        return $('body').bind('keypress', function(e) {
          return _this.dispatch(e.which);
        });
      };

      Core.prototype.dispatch = function(e) {
        console.log("keypress evt fired " + e.which);
        this.loadingController.unload();
        return this.screen1Controller.load();
      };

      return Core;

    })();
  });

}).call(this);
