// Generated by CoffeeScript 1.4.0
(function() {

  define(['jquery'], function($) {
    var Screen1Controller;
    return Screen1Controller = (function() {

      function Screen1Controller(view) {
        this.view = view;
        console.log("Screen1 constructor");
      }

      Screen1Controller.prototype.load = function() {
        console.log("Screen1 Load");
        return this.view.show();
      };

      Screen1Controller.prototype.unload = function() {
        console.log("Screen1 Unloading");
        return this.view.hide();
      };

      return Screen1Controller;

    })();
  });

}).call(this);
