// Generated by CoffeeScript 1.4.0
(function() {

  define(['jquery'], function($) {
    var LoadingView;
    return LoadingView = (function() {

      function LoadingView(divId) {
        this.divId = divId;
        console.log("View constructor");
      }

      LoadingView.prototype.show = function() {
        console.log("Show Loading");
        return $(this.divId).show();
      };

      LoadingView.prototype.hide = function() {
        console.log("Hide Loading");
        return $(this.divId).hide();
      };

      return LoadingView;

    })();
  });

}).call(this);
