// Generated by CoffeeScript 1.4.0
(function() {

  define(['jquery'], function($) {
    var Screen1View;
    return Screen1View = (function() {

      function Screen1View(divId) {
        this.divId = divId;
        console.log("View constructor");
      }

      Screen1View.prototype.show = function() {
        console.log("Show Screen1");
        return $(this.divId).show();
      };

      Screen1View.prototype.hide = function() {
        console.log("Hide Screen1");
        return $(this.divId).hide();
      };

      return Screen1View;

    })();
  });

}).call(this);
